server:
  port: ${PORT:8761}
security:
  user:
    password: ${eureka.password}

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    securePortEnabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}
